### ISSUE TITLE
`npm audit` warns about vulnerabilites

### ISSUE THREAD

**Issue by ChristophP** [dmy/elm-doc-preview#28]
Hi,

I have `elm-doc-preview` in my package.json's devDependencies. It's really cool to use :-) However, since I added it, github and npm complain about vulnerabilities.

Would be nice if they could be fixed. Maybe running `npm audit fix` will be enough. If not it would require manual review.

**Comment by rlefevre** [comment]
It was fixed in master but not yet published. I have published 3.0.3 that should fix github complains. 
Please confirm.

Note that I only fixed critical vulnerabilities because I keep nodejs 6 compatibility for now and this requires using some dependencies with a lot of lower level vulnerabilities that would be harder to fix (a PR that fix them without breaking nodejs 6 compatibility would be welcome though).

**Comment by rlefevre** [comment]
Published version 3.0.4 actually fixes all known vulnerabilities.

**Comment by ChristophP** [comment]
awesome thanks :-) I can confirm that all vulnerabilites are gone.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/5880236/67768752-75f91b00-fa53-11e9-9bfe-fdc552992ad9.png">
